spring:
  datasource:
    url: jdbc:postgresql://localhost:2022/products-api
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}